### ISSUE TITLE
Define collections of channels that can be enabled/disabled together

### ISSUE THREAD

**Issue by sestei** [sestei/pydaqconfig#2]
Often we want to acquire a certain set/collection of channels when we start an experiment, and then want to stop acquisition when the experiment is finished. Therefore, add the possibility to define a set of channels which can then be acquired together with a single click.
The list of channels could e.g. be read from a simple text file, which can be opened via the menu.
Open question: should e.g. datarate also be defined in that text file? Or is that defined in the normal way, i.e. per channel in the GUI?

**Comment by SeanDS** [comment]
When you create a channel, you choose a channel name that usually implies the purpose (e.g. "SEISMIC_X"), and this in turn implies the data rate. As long as we assume channels will remain in place for the duration of the experiment, then I think it's safe to avoid having data rates settable in the channel collection text file.

You also potentially run into problems with channels changing data rates... I can't remember exactly what happens but I don't think it's a good idea.
